---
deployment:
  tasks:
    - mkdir -p /home/hcispanel/public_html/ga-messenger.hcis.live
    - git ls-files -z | rsync -av --files-from=- --from0 ./ /home/hcispanel/public_html/ga-messenger.hcis.live/
